version: '3'
services:

    nginx:
        container_name: OrderManagementApiNginx
        image: nginx:latest
        ports:
          - "80:80"
        links:
          - php
        volumes:
          - ./:/var/www/OrderManagement
          - ./images/nginx/vhost.conf:/etc/nginx/conf.d/OrderManagement.conf
        working_dir:
          /var/www/OrderManagement

    php:
        container_name: OrderManagementApiPHPFPM
        build: ./images/php-fpm
        ports:
          - "9000:9000"
        links:
          - db
        volumes:
          - ./:/var/www/OrderManagement
          - ./images/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        working_dir:
          /var/www/OrderManagement

    db:
        container_name: OrderManagementApiDatabase
        image: mysql:5.7
        ports:
          - "3306:3306"
        volumes:
          - data:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: OrderManagement
          MYSQL_USER: OrderManagement
          MYSQL_PASSWORD: OrderManagement

volumes:
  data: